projects:
  buddirunv1:
    schemaPath: amplify/backend/api/buddirunv1/build/schema.graphql
    includes:
      - react-amplified/src/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: react-amplified/src/graphql
        region: us-west-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
